### ISSUE TITLE
test failure (DirectivesSpec) in Scala 2.12 community build

### ISSUE THREAD

**Issue by SethTisue** [typesafehub/akka-contrib-extra#74]
seen at e.g. https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/2557/consoleFull :

```
[akka-contrib-extra] [info] DirectivesSpec:
[akka-contrib-extra] [info] accept directive
[akka-contrib-extra] [info] - should pass to inner route if a matching accept header is present
[akka-contrib-extra] [info] - should reject if no requested accept header is present
[akka-contrib-extra] [info] parameterList directive
[akka-contrib-extra] [info] - should provide a list of parameters to the inner route *** FAILED ***
[akka-contrib-extra] [info]   "List([1, 2, 3])" was not equal to "List([3, 2, 1])" (DirectivesSpec.scala:41)
```

in the context of the community build, I'll just disable running the tests. we had only added akka-contrib-extra to the community build in the first place because it was a dependency of conductr-lib

maintainers of this repo: feel free to pursue or ignore as you see fit

**Comment by SethTisue** [comment]
oh you know what, we're building a version of akka-contrib-extra that we forked in December 2016 because the version of bintray-sbt used here wasn't dbuild-friendly. so it's possible this isn't even a current report.

if a maintainer here lets me know that this repo is still active, I can try refreshing our fork and see if the problem goes away. but if this repo is now moribund, then no worries.

**Comment by ktoso** [comment]
FYI Akka team does not maintain this repo; It was originally a conductr thing, so now perhaps @longshorej should decide if its still alive.

**Comment by longshorej** [comment]
I currently maintain this repo and will at least until ConductR's EOL (Tentatively 2019-01-31) -- it exists only to serve ConductR at this point.

I think the only particularly useful functionality here is `NonBlockingProcess` which perhaps should end up in Alpakka. I'll discuss at a later date with Akka team whether or not that's a good idea.

Otherwise, I don't see the need to spend much too time on this. If it's quick enough to run the tests against `master` I'd be curious if that succeeds, otherwise I think it's fine to simply disable them in the community build.

**Comment by 2m** [comment]
Previously CI did not run tests on 2.12 until #77 and it seems [to be fine](https://travis-ci.org/typesafehub/akka-contrib-extra/builds/413992854) now. Therefore closing this.
